# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hi, I’m Gavin, a content designer # displayed on home page
home_title_meta: Gavin Wray - Content designer # populates the <title> tag
description: I help organisations to simplify their services with clear language and user-centred design # displayed on home page

# baseurl: "/athena" # the subpath of your site, e.g. /blog
url: "https://www.gavinwray.com" # the base hostname & protocol for your site
github_repo: athena # the GitHub repo name for your project
github_username: gavinwray
language: en
author: Gavin Wray

permalink: /:year/:month/:day/:title/

# Theme
remote_theme: gavinwray/athena

# Optional social link, you can choose from the following options:
# Twitter (default), Instagram, Medium or Dribbble
social_link: twitter
social_username: gavinwray

# Google Analytics tracking ID UA-XXXXXXX-X
google_analytics: UA—1414709-1

# Build settings
markdown: kramdown